<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.x6xwwrw' shared service.

return $this->services['service_locator.x6xwwrw'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('profileRepository' => function () {
    $f = function (\App\Repository\ProfileRepository $v = null) { return $v; }; return $f(${($_ = isset($this->services['App\Repository\ProfileRepository']) ? $this->services['App\Repository\ProfileRepository'] : $this->load('getProfileRepositoryService.php')) && false ?: '_'});
}));
