<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\ProfileController:index' => function () {
    return ${($_ = isset($this->services['service_locator.x6xwwrw']) ? $this->services['service_locator.x6xwwrw'] : $this->load('getServiceLocator_X6xwwrwService.php')) && false ?: '_'};
}, 'App\\Controller\\SignupCompanyController:registerAction' => function () {
    return ${($_ = isset($this->services['service_locator.hazzr0s']) ? $this->services['service_locator.hazzr0s'] : $this->load('getServiceLocator_Hazzr0sService.php')) && false ?: '_'};
}, 'App\\Controller\\SignupUserController:registerAction' => function () {
    return ${($_ = isset($this->services['service_locator.jecnx6k']) ? $this->services['service_locator.jecnx6k'] : $this->load('getServiceLocator_Jecnx6kService.php')) && false ?: '_'};
}, 'App\\Controller\\ProfileController::index' => function () {
    return ${($_ = isset($this->services['service_locator.x6xwwrw']) ? $this->services['service_locator.x6xwwrw'] : $this->load('getServiceLocator_X6xwwrwService.php')) && false ?: '_'};
}, 'App\\Controller\\SignupCompanyController::registerAction' => function () {
    return ${($_ = isset($this->services['service_locator.hazzr0s']) ? $this->services['service_locator.hazzr0s'] : $this->load('getServiceLocator_Hazzr0sService.php')) && false ?: '_'};
}, 'App\\Controller\\SignupUserController::registerAction' => function () {
    return ${($_ = isset($this->services['service_locator.jecnx6k']) ? $this->services['service_locator.jecnx6k'] : $this->load('getServiceLocator_Jecnx6kService.php')) && false ?: '_'};
})));
