#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
homepage:
    path: /
    controller: App\Controller\HomeController::index
    defaults:
        template: homepage.html.twig

signup:
    path: /signup
    controller: App\Controller\SignupController::index
    defaults:
        template: registration.html.twig


signupUser:
    path: /signupUser
    controller: App\Controller\SignupUserController::index
    defaults:
        template: registrationUsers.html.twig

signupCompany:
    path: /signupCompany
    controller: App\Controller\SignupCompanyController::index
    defaults:
        template: registrationCompanies.html.twig
deleteService:
    path: /company/services/delete/{id}
    controller: App\Controller\ServiceListController::Delete
    defaults:
        template: serviceList.html.twig
editService:
    path: /company/services/edit/{id}
    controller: App\Controller\ServiceListController::Edit
    defaults:
        template: serviceList.html.twig
carServices:
    path: /user/carServices/{id}"
    controller: App\Controller\CarServiceListController::index
    defaults:
        template: carServiceList.html.twig