<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxb7bgz\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxb7bgz/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFxb7bgz.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFxb7bgz\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFxb7bgz\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Fxb7bgz',
    'container.build_id' => 'bf0ce891',
    'container.build_time' => 1524063039,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFxb7bgz');
