<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPl1vwxa\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPl1vwxa/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPl1vwxa.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPl1vwxa\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerPl1vwxa\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Pl1vwxa',
    'container.build_id' => '121d302c',
    'container.build_time' => 1524500677,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPl1vwxa');
