<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFon7jgx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFon7jgx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFon7jgx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFon7jgx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFon7jgx\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Fon7jgx',
    'container.build_id' => 'c3aa6cd1',
    'container.build_time' => 1524425455,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFon7jgx');
